services:
  - type: web
    name: movie-agent
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p data
      mkdir -p config
    startCommand: python start_render.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DISABLE_SELENIUM
        value: "true"
      - key: FLASK_SECRET_KEY
        generateValue: true
    disk:
      name: movie-agent-disk
      mountPath: /opt/render/project/src/data
      sizeGB: 1